---
- name: Apply updates (dnf/yum)
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  when: ansible_facts['pkg_mgr'] in ['dnf', 'yum']

- name: Apply updates (apt)
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  become: true
  when: ansible_facts['pkg_mgr'] == 'apt'
