health_check_url: "http://192.168.1.114:3000"
health_check_podman_user: deploy
health_check_containers:
  - database
  - redis
  - guacd
  - patchmon_server_1

podman_units:
  - name: database
    scope: user
  - name: redis
    scope: user
  - name: guacd
    scope: user
  - name: patchmon_server_1
    service_name: patchmon-server
    scope: user
